import { CompanyProfile } from '@/types/interview';

export const COMPANY_LIST: CompanyProfile[] = [
  {
    id: 'bytedance',
    name: '字节跳动',
    nameEn: 'ByteDance',
    logo: '🔥',
    color: '#3C8CFF',
    interviewStyle: '高压快节奏，追问深，强调编码质量和思考速度。',
    techStack: ['React', 'Vue', 'Go', '分布式', '算法'],
    cultureKeywords: ['务实', '高效', '结果导向'],
    rounds: [
      { round: 'first', focus: '基础与项目深挖', duration: 45 },
      { round: 'second', focus: '系统设计与复杂场景', duration: 60 },
      { round: 'third', focus: '综合评估', duration: 45 },
      { round: 'hr', focus: '价值观匹配', duration: 30 },
    ],
  },
  {
    id: 'alibaba',
    name: '阿里巴巴',
    nameEn: 'Alibaba',
    logo: '🟠',
    color: '#FF6A00',
    interviewStyle: '注重系统性思维，偏好业务理解与工程落地。',
    techStack: ['Java', 'Spring', '中间件', 'MySQL', '系统设计'],
    cultureKeywords: ['客户第一', '拥抱变化', '团队协作'],
    rounds: [
      { round: 'first', focus: '基础与八股', duration: 45 },
      { round: 'second', focus: '架构设计', duration: 60 },
      { round: 'third', focus: '项目价值与业务理解', duration: 45 },
      { round: 'hr', focus: '文化匹配', duration: 30 },
    ],
  },
  {
    id: 'tencent',
    name: '腾讯',
    nameEn: 'Tencent',
    logo: '🐧',
    color: '#07C160',
    interviewStyle: '强调基础扎实，网络和系统底层能力要求高。',
    techStack: ['C++', 'Linux', '网络协议', '后台开发'],
    cultureKeywords: ['长期主义', '稳定', '技术深度'],
    rounds: [
      { round: 'first', focus: '基础知识', duration: 45 },
      { round: 'second', focus: '场景设计', duration: 60 },
      { round: 'third', focus: '综合能力评估', duration: 45 },
      { round: 'hr', focus: '团队协同', duration: 30 },
    ],
  },
  {
    id: 'meituan',
    name: '美团',
    nameEn: 'Meituan',
    logo: '🟡',
    color: '#FFD100',
    interviewStyle: '实战导向，关注业务场景和工程可交付性。',
    techStack: ['Java', 'Redis', 'MySQL', '高并发'],
    cultureKeywords: ['效率', '执行力', '业务驱动'],
    rounds: [
      { round: 'first', focus: '技术基础', duration: 45 },
      { round: 'second', focus: '业务场景设计', duration: 60 },
      { round: 'third', focus: '项目复盘', duration: 45 },
      { round: 'hr', focus: '动机与职业规划', duration: 30 },
    ],
  },
  {
    id: 'xiaohongshu',
    name: '小红书',
    nameEn: 'Xiaohongshu',
    logo: '📕',
    color: '#FF2442',
    interviewStyle: '关注用户体验与增长场景，重前后端协同。',
    techStack: ['React', 'Node.js', '推荐系统', '性能优化'],
    cultureKeywords: ['用户价值', '创意', '执行'],
    rounds: [
      { round: 'first', focus: '基础与项目', duration: 45 },
      { round: 'second', focus: '系统和性能', duration: 60 },
      { round: 'third', focus: '团队合作', duration: 45 },
      { round: 'hr', focus: '文化匹配', duration: 30 },
    ],
  },
  {
    id: 'pdd',
    name: '拼多多',
    nameEn: 'Pinduoduo',
    logo: '🟤',
    color: '#E2231A',
    interviewStyle: '节奏快，重问题拆解能力与性能意识。',
    techStack: ['Go', 'Java', '分布式', '高并发'],
    cultureKeywords: ['效率', '实战', '结果'],
    rounds: [
      { round: 'first', focus: '基础与编码', duration: 45 },
      { round: 'second', focus: '高并发设计', duration: 60 },
      { round: 'third', focus: '业务落地能力', duration: 45 },
      { round: 'hr', focus: '稳定性与抗压', duration: 30 },
    ],
  },
];

export const COMPANY_MAP = Object.fromEntries(COMPANY_LIST.map((item) => [item.id, item]));
